from src.schemas.coupon_package import Package, RestaurantCoupon
from src.schemas.restaurant import Coupon, Restaurant

RESTAURANTS: list[Restaurant] = [
    Restaurant(
        id="rest_001",
        name="轻食花园餐厅",
        tags=["healthy", "low_calorie", "kid_friendly", "salad", "light"],
        near_location="venue_001",
        distance_from_venue_km=0.8,
        avg_price_per_person=86.0,
        rating=4.6,
        open_time="11:00",
        close_time="21:00",
        queue_minutes=15,
        noise_level="quiet",
        reservation_available=True,
        has_kids_menu=True,
        has_low_calorie_options=True,
        available_seats=12,
        available_slots=["17:00", "17:30", "18:00", "18:30"],
        suggested_meal_duration_min=60,
        suggested_meal_duration_max=90,
        review_count=860,
        positive_review_tags=["食材新鲜", "摆盘精致", "适合减脂"],
        negative_review_tags=["份量偏小"],
        recommended_dishes=["鸡胸藜麦沙拉", "牛油果吐司", "低卡冰美式"],
        specialty_tags=["健康轻食"],
        area="云景",
        nearby_areas=["晨阳区", "星桥"],
        packages=[
            Package(
                id="pkg_rest001_1",
                title="轻食三人套餐",
                price=198.0,
                original_price=258.0,
                includes=["主食×3", "饮品×3"],
            )
        ],
        restaurant_coupons=[
            RestaurantCoupon(
                id="rc_001",
                title="满100减15",
                discount_type="fixed",
                value=15.0,
                min_spend=100.0,
                available=True,
            )
        ],
    ),
    Restaurant(
        id="rest_002",
        name="樱花日式料理",
        tags=["japanese", "healthy", "photo", "social", "kid_friendly"],
        near_location="venue_001",
        distance_from_venue_km=1.2,
        avg_price_per_person=110.0,
        rating=4.7,
        open_time="11:30",
        close_time="22:00",
        queue_minutes=30,
        noise_level="quiet",
        reservation_available=True,
        has_kids_menu=True,
        has_low_calorie_options=True,
        available_seats=8,
        available_slots=["17:30", "18:00", "19:00"],
        suggested_meal_duration_min=60,
        suggested_meal_duration_max=90,
        review_count=1340,
        positive_review_tags=["刺身新鲜", "摆盘好看", "服务周到"],
        negative_review_tags=["节假日排队长", "价格稍贵"],
        recommended_dishes=["刺身拼盘", "鳗鱼饭", "天妇罗套餐", "寿司卷"],
        specialty_tags=["情侣首选", "网红打卡"],
        area="云景",
        nearby_areas=["晨阳区", "星桥"],
        packages=[
            Package(
                id="pkg_rest002_1",
                title="双人精选套餐",
                price=168.0,
                original_price=220.0,
                includes=["双人刺身拼盘", "寿司×6", "饮品×2"],
            )
        ],
        restaurant_coupons=[
            RestaurantCoupon(
                id="rc_002",
                title="满150减20",
                discount_type="fixed",
                value=20.0,
                min_spend=150.0,
                available=True,
            )
        ],
    ),
    Restaurant(
        id="rest_003",
        name="老街麻辣火锅",
        tags=["hotpot", "social", "friends", "spicy"],
        near_location="venue_002",
        distance_from_venue_km=0.6,
        avg_price_per_person=95.0,
        rating=4.5,
        open_time="11:00",
        close_time="23:00",
        queue_minutes=45,
        noise_level="loud",
        reservation_available=True,
        has_kids_menu=False,
        has_low_calorie_options=False,
        available_seats=0,
        available_slots=["17:00", "18:00", "19:00", "20:00"],
        suggested_meal_duration_min=90,
        suggested_meal_duration_max=120,
        review_count=2100,
        positive_review_tags=["锅底香", "毛肚嫩", "朋友聚餐首选"],
        negative_review_tags=["节假日排队1小时+", "味道偏辣"],
        recommended_dishes=["毛肚", "肥牛卷", "虾滑", "麻辣红汤锅底"],
        specialty_tags=["朋友聚餐"],
        area="晨阳区",
        nearby_areas=["云景", "竞技园"],
    ),
    Restaurant(
        id="rest_004",
        name="家常小馆",
        tags=["chinese", "homestyle", "kid_friendly", "affordable"],
        near_location="venue_002",
        distance_from_venue_km=0.5,
        avg_price_per_person=55.0,
        rating=4.3,
        open_time="10:00",
        close_time="21:00",
        queue_minutes=10,
        noise_level="moderate",
        reservation_available=False,
        has_kids_menu=True,
        has_low_calorie_options=False,
        available_seats=30,
        available_slots=[],
        suggested_meal_duration_min=60,
        suggested_meal_duration_max=90,
        review_count=740,
        positive_review_tags=["家常味道", "性价比高", "分量足"],
        negative_review_tags=["环境一般"],
        recommended_dishes=["红烧肉", "蒸鸡蛋", "番茄炒蛋", "小米粥"],
        specialty_tags=["实惠家常"],
        area="晨阳区",
        nearby_areas=["云景", "竞技园"],
    ),
    Restaurant(
        id="rest_005",
        name="西式简餐咖啡馆",
        tags=["western", "cafe", "photo", "social", "friends", "low_calorie"],
        near_location="venue_005",
        distance_from_venue_km=0.5,
        avg_price_per_person=75.0,
        rating=4.4,
        open_time="08:00",
        close_time="22:00",
        queue_minutes=20,
        noise_level="moderate",
        reservation_available=True,
        has_kids_menu=False,
        has_low_calorie_options=True,
        available_seats=16,
        available_slots=["17:00", "17:30", "18:00", "18:30", "19:00"],
        suggested_meal_duration_min=45,
        suggested_meal_duration_max=75,
        review_count=920,
        positive_review_tags=["咖啡好喝", "拍照出片", "氛围轻松"],
        negative_review_tags=["高峰期等位"],
        recommended_dishes=["牛排套餐", "意式浓缩", "拿铁", "班尼迪克蛋"],
        specialty_tags=["网红咖啡", "情侣首选"],
        area="芳华街",
        nearby_areas=["晨阳区", "运动园"],
        restaurant_coupons=[
            RestaurantCoupon(
                id="rc_005",
                title="满80减10",
                discount_type="fixed",
                value=10.0,
                min_spend=80.0,
                available=True,
            )
        ],
    ),
    Restaurant(
        id="rest_006",
        name="博物馆旁面馆",
        tags=["noodles", "chinese", "quick", "affordable", "kid_friendly"],
        near_location="venue_003",
        distance_from_venue_km=0.5,
        avg_price_per_person=40.0,
        rating=4.2,
        open_time="09:00",
        close_time="20:00",
        queue_minutes=5,
        noise_level="moderate",
        reservation_available=False,
        has_kids_menu=True,
        has_low_calorie_options=False,
        available_seats=25,
        available_slots=[],
        suggested_meal_duration_min=30,
        suggested_meal_duration_max=60,
        review_count=480,
        positive_review_tags=["面条劲道", "性价比极高", "出餐快"],
        negative_review_tags=["环境较嘈"],
        recommended_dishes=["招牌炸酱面", "麻酱凉面", "番茄牛腩面"],
        specialty_tags=["快捷实惠"],
        area="明湖区",
        nearby_areas=["学海村", "古城区"],
    ),
    Restaurant(
        id="rest_007",
        name="精品烤肉居",
        tags=["bbq", "social", "friends", "grilled", "night_out"],
        near_location="venue_009",
        distance_from_venue_km=0.4,
        avg_price_per_person=130.0,
        rating=4.6,
        open_time="17:00",
        close_time="01:00",
        queue_minutes=35,
        noise_level="loud",
        reservation_available=True,
        has_kids_menu=False,
        has_low_calorie_options=False,
        available_seats=18,
        available_slots=["17:30", "18:00", "19:00", "20:00"],
        suggested_meal_duration_min=90,
        suggested_meal_duration_max=120,
        review_count=1560,
        positive_review_tags=["牛肉品质好", "烤炉自助趣", "适合聚会"],
        negative_review_tags=["节假日必须提前预约", "烟气较大"],
        recommended_dishes=["和牛牛肉", "五花肉", "秘制腌肉", "烤串拼盘"],
        specialty_tags=["朋友聚餐", "夜生活首选"],
        area="芳华街",
        nearby_areas=["晨阳区", "运动园"],
        packages=[
            Package(
                id="pkg_rest007_1",
                title="四人烤肉套餐",
                price=448.0,
                original_price=520.0,
                includes=["精选肉拼×4", "小菜×4", "饮品×4"],
            )
        ],
        restaurant_coupons=[
            RestaurantCoupon(
                id="rc_007",
                title="满200减30",
                discount_type="fixed",
                value=30.0,
                min_spend=200.0,
                available=True,
            )
        ],
    ),
    Restaurant(
        id="rest_008",
        name="静庭中式茶餐",
        tags=["chinese", "quiet", "elderly_friendly", "low_calorie", "healthy", "tea"],
        near_location="venue_008",
        distance_from_venue_km=0.4,
        avg_price_per_person=65.0,
        rating=4.5,
        open_time="10:00",
        close_time="21:00",
        queue_minutes=5,
        noise_level="quiet",
        reservation_available=True,
        has_kids_menu=False,
        has_low_calorie_options=True,
        available_seats=20,
        available_slots=["16:00", "17:00", "17:30", "18:00"],
        suggested_meal_duration_min=60,
        suggested_meal_duration_max=90,
        review_count=670,
        positive_review_tags=["清淡健康", "适合老人", "环境安静"],
        negative_review_tags=["菜品种类少"],
        recommended_dishes=["砂锅粥", "清蒸鱼", "时蔬炒豆腐", "茉莉花茶"],
        specialty_tags=["长辈推荐", "健康清淡"],
        area="古城区",
        nearby_areas=["南市", "旧市巷"],
    ),
    Restaurant(
        id="rest_009",
        name="商务简餐吧",
        tags=["western", "business_casual", "not_too_private", "group_friendly", "colleagues"],
        near_location="venue_007",
        distance_from_venue_km=0.5,
        avg_price_per_person=88.0,
        rating=4.3,
        open_time="11:00",
        close_time="22:00",
        queue_minutes=8,
        noise_level="moderate",
        reservation_available=True,
        has_kids_menu=False,
        has_low_calorie_options=True,
        available_seats=24,
        available_slots=["17:00", "17:30", "18:00", "18:30", "19:00"],
        suggested_meal_duration_min=60,
        suggested_meal_duration_max=90,
        review_count=520,
        positive_review_tags=["适合商务聚餐", "包厢隐私好", "菜品稳定"],
        negative_review_tags=["价格偏中上"],
        recommended_dishes=["牛排", "意面套餐", "披萨", "商务套餐"],
        specialty_tags=["团建首选"],
        area="学府路",
        nearby_areas=["明湖区", "学海村"],
        restaurant_coupons=[
            RestaurantCoupon(
                id="rc_009",
                title="满200减25",
                discount_type="fixed",
                value=25.0,
                min_spend=200.0,
                available=True,
            )
        ],
    ),
    Restaurant(
        id="rest_010",
        name="咖啡轻食工坊",
        tags=["coffee", "couple", "photo", "low_calorie", "romantic", "cafe"],
        near_location="venue_011",
        distance_from_venue_km=0.6,
        avg_price_per_person=72.0,
        rating=4.5,
        open_time="09:00",
        close_time="22:00",
        queue_minutes=12,
        noise_level="quiet",
        reservation_available=True,
        has_kids_menu=False,
        has_low_calorie_options=True,
        available_seats=14,
        available_slots=["16:30", "17:00", "17:30", "18:00", "18:30"],
        suggested_meal_duration_min=30,
        suggested_meal_duration_max=60,
        review_count=1020,
        positive_review_tags=["咖啡香浓", "甜点精致", "氛围感强"],
        negative_review_tags=["座位稍少"],
        recommended_dishes=["手冲咖啡", "抹茶拿铁", "提拉米苏", "法式可颂"],
        specialty_tags=["情侣首选", "网红咖啡"],
        area="云景",
        nearby_areas=["晨阳区", "星桥"],
        restaurant_coupons=[
            RestaurantCoupon(
                id="rc_010",
                title="第二杯咖啡半价",
                discount_type="percent",
                value=0.5,
                min_spend=0.0,
                available=True,
            )
        ],
    ),
    Restaurant(
        id="rest_011",
        name="亲子主题餐厅",
        tags=["kid_friendly", "family_friendly", "young_child", "parent_child", "themed"],
        near_location="venue_012",
        distance_from_venue_km=0.5,
        avg_price_per_person=95.0,
        rating=4.7,
        open_time="10:30",
        close_time="21:00",
        queue_minutes=15,
        noise_level="moderate",
        reservation_available=True,
        has_kids_menu=True,
        has_low_calorie_options=True,
        available_seats=20,
        available_slots=["17:00", "17:30", "18:00", "18:30"],
        suggested_meal_duration_min=60,
        suggested_meal_duration_max=90,
        review_count=1180,
        positive_review_tags=["儿童餐丰富", "主题装饰可爱", "孩子喜欢"],
        negative_review_tags=["价格偏高"],
        recommended_dishes=["恐龙形儿童套餐", "卡通饭团", "蔬菜汤", "亲子拼盘"],
        specialty_tags=["亲子推荐"],
        area="明湖区",
        nearby_areas=["学海村", "学府路"],
        packages=[
            Package(
                id="pkg_rest011_1",
                title="亲子套餐（1大1小）",
                price=148.0,
                original_price=190.0,
                includes=["儿童套餐×1", "成人主食×1", "饮品×2"],
            )
        ],
    ),
    Restaurant(
        id="rest_012",
        name="深夜拉面馆",
        tags=["japanese", "ramen", "affordable", "quick", "friends", "casual"],
        near_location="venue_009",
        distance_from_venue_km=0.5,
        avg_price_per_person=58.0,
        rating=4.4,
        open_time="11:00",
        close_time="02:00",
        queue_minutes=10,
        noise_level="moderate",
        reservation_available=False,
        has_kids_menu=False,
        has_low_calorie_options=False,
        available_seats=22,
        available_slots=[],
        suggested_meal_duration_min=30,
        suggested_meal_duration_max=60,
        review_count=1090,
        positive_review_tags=["汤头鲜美", "面条Q弹", "性价比高"],
        negative_review_tags=["座位较少"],
        recommended_dishes=["浓厚豚骨拉面", "叉烧拉面", "温泉蛋", "溏心蛋"],
        specialty_tags=["夜宵首选"],
        area="芳华街",
        nearby_areas=["晨阳区", "运动园"],
    ),
    # MVP-4 expansion: additional restaurants for richer demo coverage
    Restaurant(
        id="rest_013",
        name="烛光西餐厅",
        tags=["western", "romantic", "couple", "candlelight", "quiet", "date"],
        near_location="venue_009",
        distance_from_venue_km=3.2,
        avg_price_per_person=320.0,
        rating=4.6,
        open_time="17:00",
        close_time="22:00",
        queue_minutes=0,
        noise_level="quiet",
        reservation_available=True,
        has_kids_menu=False,
        has_low_calorie_options=True,
        available_seats=40,
        available_slots=["17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
        suggested_meal_duration_min=90,
        suggested_meal_duration_max=120,
        review_count=1340,
        positive_review_tags=["浪漫氛围", "服务细腻", "适合约会"],
        negative_review_tags=["价格偏高", "需提前预约"],
        recommended_dishes=["干式熟成牛排", "松露意面", "烛光套餐"],
        specialty_tags=["情侣首选", "纪念日"],
        area="芳华街",
        nearby_areas=["云景"],
        packages=[
            Package(
                id="pkg_rest013_1",
                title="双人烛光套餐",
                price=560.0,
                original_price=680.0,
                includes=["前菜×2", "主菜×2", "甜点×2", "饮品×2"],
            )
        ],
    ),
    Restaurant(
        id="rest_014",
        name="清晨面包坊",
        tags=[
            "brunch",
            "coffee",
            "light",
            "morning",
            "couple",
            "solo",
            "quiet",
            "healthy",
        ],
        near_location="venue_003",
        distance_from_venue_km=2.8,
        avg_price_per_person=65.0,
        rating=4.4,
        open_time="08:00",
        close_time="14:00",
        queue_minutes=10,
        noise_level="quiet",
        reservation_available=False,
        has_kids_menu=True,
        has_low_calorie_options=True,
        available_seats=35,
        available_slots=[],
        suggested_meal_duration_min=45,
        suggested_meal_duration_max=75,
        review_count=940,
        positive_review_tags=["环境舒适", "面包新鲜", "早午餐宝藏"],
        negative_review_tags=["下午不营业", "座位有限"],
        recommended_dishes=["招牌可颂", "班尼迪克蛋", "特调冷萃咖啡"],
        specialty_tags=["早午餐", "文艺小店"],
        area="明湖区",
        nearby_areas=["学海村"],
        restaurant_coupons=[
            RestaurantCoupon(
                id="rc_014",
                title="消费满60立减10",
                discount_type="fixed",
                value=10.0,
                min_spend=60.0,
                available=True,
            )
        ],
    ),
    Restaurant(
        id="rest_015",
        name="深夜拉面馆·晨阳店",
        tags=["japanese", "ramen", "late_night", "friends", "solo", "casual"],
        near_location="venue_015",
        distance_from_venue_km=4.1,
        avg_price_per_person=75.0,
        rating=4.5,
        open_time="18:00",
        close_time="02:00",
        queue_minutes=15,
        noise_level="moderate",
        reservation_available=False,
        has_kids_menu=False,
        has_low_calorie_options=False,
        available_seats=30,
        available_slots=[],
        suggested_meal_duration_min=30,
        suggested_meal_duration_max=60,
        review_count=820,
        positive_review_tags=["汤头浓郁", "深夜救援", "性价比高"],
        negative_review_tags=["凌晨人多", "不接受预约"],
        recommended_dishes=["浓郁豚骨拉面", "盐味鸡汤拉面", "半熟溏心蛋"],
        specialty_tags=["深夜食堂", "日式正宗"],
        area="晨阳区",
        nearby_areas=["东河区", "芳华街"],
    ),
    Restaurant(
        id="rest_016",
        name="动物园亲子餐厅",
        tags=["family_friendly", "kids_menu", "chinese", "casual", "parent_child"],
        near_location="venue_014",
        distance_from_venue_km=0.5,
        avg_price_per_person=85.0,
        rating=4.2,
        open_time="09:00",
        close_time="18:00",
        queue_minutes=10,
        noise_level="moderate",
        reservation_available=True,
        has_kids_menu=True,
        has_low_calorie_options=False,
        available_seats=40,
        available_slots=["11:00", "11:30", "12:00", "12:30", "13:00", "13:30"],
        suggested_meal_duration_min=45,
        suggested_meal_duration_max=75,
        review_count=680,
        positive_review_tags=["适合亲子", "分量足", "孩子喜欢"],
        negative_review_tags=["价格偏高", "周末排队"],
        recommended_dishes=["儿童套餐", "农家大盘鸡", "动物造型蛋糕"],
        specialty_tags=["亲子主题", "园区配套"],
        area="远郊区",
        nearby_areas=["晨阳区"],
    ),
]

COUPONS: list[Coupon] = [
    Coupon(
        id="coupon_001",
        target_id="rest_001",
        target_type="restaurant",
        title="轻食三人套餐券",
        price=198.0,
        original_price=258.0,
        valid_until="2026-12-31",
        available=True,
    ),
    Coupon(
        id="coupon_002",
        target_id="venue_001",
        target_type="venue",
        title="亲子乐园3人票套餐",
        price=220.0,
        original_price=264.0,
        valid_until="2026-12-31",
        available=True,
    ),
    Coupon(
        id="coupon_003",
        target_id="rest_002",
        target_type="restaurant",
        title="日料双人套餐",
        price=168.0,
        original_price=220.0,
        valid_until="2026-12-31",
        available=True,
    ),
    Coupon(
        id="coupon_004",
        target_id="rest_005",
        target_type="restaurant",
        title="咖啡馆四人下午茶套餐",
        price=168.0,
        original_price=220.0,
        valid_until="2026-12-31",
        available=True,
    ),
]

_REST_MAP: dict[str, Restaurant] = {r.id: r for r in RESTAURANTS}
_COUPON_MAP: dict[str, Coupon] = {c.id: c for c in COUPONS}


def get_restaurant(restaurant_id: str) -> Restaurant | None:
    return _REST_MAP.get(restaurant_id)


def get_coupon(coupon_id: str) -> Coupon | None:
    return _COUPON_MAP.get(coupon_id)


def search_restaurants(
    near_location: str,
    group_size: int,
    preferences: list[str],
) -> list[Restaurant]:
    results = []
    for r in RESTAURANTS:
        if r.near_location != near_location:
            continue
        if preferences and not any(p in r.tags for p in preferences):
            continue
        results.append(r)
    if not results:
        results = [r for r in RESTAURANTS if r.near_location == near_location]
    return sorted(results, key=lambda r: (-r.rating, r.queue_minutes))


def get_coupons_for(target_id: str) -> list[Coupon]:
    return [c for c in COUPONS if c.target_id == target_id and c.available]
