from src.schemas.coupon_package import Package, TicketOption, VenueCoupon
from src.schemas.venue import Venue

VENUES: list[Venue] = [
    Venue(
        id="venue_001",
        name="森林亲子乐园",
        type="kids_playground",
        tags=["parent_child", "kids", "indoor", "family_friendly"],
        distance_km=3.2,
        suggested_duration_minutes=120,
        suggested_duration_min=90,
        suggested_duration_max=180,
        duration_flexibility="medium",
        suitable_age_min=3,
        suitable_age_max=12,
        open_time="09:00",
        close_time="20:00",
        price_per_person=88.0,
        rating=4.7,
        indoor=True,
        requires_ticket=True,
        available_tickets=30,
        walk_intensity="low",
        noise_level="loud",
        queue_minutes=20,
        review_count=1280,
        positive_review_tags=["孩子超喜欢", "设施安全干净", "适合3-10岁"],
        negative_review_tags=["节假日排队长"],
        specialty_tags=["亲子推荐"],
        area="云景",
        nearby_areas=["晨阳区", "星桥"],
        packages=[
            Package(
                id="pkg_venue001_1",
                title="家庭套票（2大1小）",
                price=220.0,
                original_price=264.0,
                includes=["成人票×2", "儿童票×1"],
            )
        ],
        venue_coupons=[
            VenueCoupon(
                id="vc_001",
                title="立减20元",
                discount_type="fixed",
                value=20.0,
                min_spend=80.0,
                available=True,
            )
        ],
    ),
    Venue(
        id="venue_002",
        name="城市湖边公园",
        type="lake_park",
        tags=["outdoor", "walk", "photo", "family_friendly", "free"],
        distance_km=2.1,
        suggested_duration_minutes=90,
        suggested_duration_min=60,
        suggested_duration_max=150,
        duration_flexibility="high",
        suitable_age_min=0,
        suitable_age_max=99,
        open_time="06:00",
        close_time="21:00",
        price_per_person=0.0,
        rating=4.5,
        indoor=False,
        requires_ticket=False,
        available_tickets=999,
        walk_intensity="medium",
        noise_level="quiet",
        queue_minutes=0,
        review_count=3560,
        positive_review_tags=["空气好", "适合遛娃", "风景美"],
        negative_review_tags=["停车位少"],
        specialty_tags=["打卡胜地"],
        area="晨阳区",
        nearby_areas=["云景", "竞技园"],
    ),
    Venue(
        id="venue_003",
        name="科技探索博物馆",
        type="museum",
        tags=["educational", "indoor", "kids", "family_friendly", "parent_child"],
        distance_km=4.8,
        suggested_duration_minutes=150,
        suggested_duration_min=90,
        suggested_duration_max=180,
        duration_flexibility="medium",
        suitable_age_min=5,
        suitable_age_max=99,
        open_time="09:30",
        close_time="17:30",
        price_per_person=60.0,
        rating=4.6,
        indoor=True,
        requires_ticket=True,
        available_tickets=50,
        walk_intensity="medium",
        noise_level="quiet",
        queue_minutes=30,
        review_count=2140,
        positive_review_tags=["互动展品丰富", "讲解员专业", "孩子学到不少"],
        negative_review_tags=["周末排队长", "停车贵"],
        specialty_tags=["亲子推荐", "科普教育"],
        area="明湖区",
        nearby_areas=["学海村", "古城区"],
        packages=[
            Package(
                id="pkg_venue003_1",
                title="家庭联票（2大2小）",
                price=168.0,
                original_price=240.0,
                includes=["成人票×2", "儿童票×2"],
            )
        ],
    ),
    Venue(
        id="venue_004",
        name="植物园温室",
        type="garden",
        tags=["outdoor", "indoor", "photo", "walk", "family_friendly", "romantic"],
        distance_km=5.5,
        suggested_duration_minutes=120,
        suggested_duration_min=60,
        suggested_duration_max=150,
        duration_flexibility="high",
        suitable_age_min=0,
        suitable_age_max=99,
        open_time="08:00",
        close_time="18:00",
        price_per_person=40.0,
        rating=4.4,
        indoor=False,
        requires_ticket=True,
        available_tickets=20,
        walk_intensity="medium",
        noise_level="quiet",
        queue_minutes=10,
        review_count=980,
        positive_review_tags=["花卉品种多", "拍照好看", "环境幽静"],
        negative_review_tags=["天热较晒"],
        specialty_tags=["情侣首选", "网红打卡"],
        area="明湖区",
        nearby_areas=["翠屏山", "锦湖园"],
        venue_coupons=[
            VenueCoupon(
                id="vc_004",
                title="双人票9折",
                discount_type="percent",
                value=0.9,
                min_spend=0.0,
                available=True,
            )
        ],
    ),
    Venue(
        id="venue_005",
        name="创意艺术中心",
        type="art_center",
        tags=["indoor", "art", "photo", "friends", "social"],
        distance_km=3.9,
        suggested_duration_minutes=100,
        suggested_duration_min=60,
        suggested_duration_max=120,
        duration_flexibility="medium",
        suitable_age_min=8,
        suitable_age_max=99,
        open_time="10:00",
        close_time="21:00",
        price_per_person=55.0,
        rating=4.3,
        indoor=True,
        requires_ticket=True,
        available_tickets=15,
        walk_intensity="low",
        noise_level="moderate",
        queue_minutes=15,
        review_count=760,
        positive_review_tags=["展览有新意", "拍照好看", "文创周边棒"],
        negative_review_tags=["展品更新慢"],
        specialty_tags=["网红打卡"],
        area="芳华街",
        nearby_areas=["晨阳区", "运动园"],
        venue_coupons=[
            VenueCoupon(
                id="vc_005",
                title="立减10元",
                discount_type="fixed",
                value=10.0,
                min_spend=55.0,
                available=True,
            )
        ],
    ),
    Venue(
        id="venue_006",
        name="室内攀岩体验馆",
        type="climbing",
        tags=["sports", "indoor", "adventure", "friends", "active"],
        distance_km=6.2,
        suggested_duration_minutes=90,
        suggested_duration_min=90,
        suggested_duration_max=120,
        duration_flexibility="low",
        suitable_age_min=10,
        suitable_age_max=50,
        open_time="10:00",
        close_time="22:00",
        price_per_person=120.0,
        rating=4.5,
        indoor=True,
        requires_ticket=True,
        available_tickets=10,
        walk_intensity="high",
        noise_level="moderate",
        queue_minutes=20,
        review_count=540,
        positive_review_tags=["教练耐心", "设施安全", "很有挑战性"],
        negative_review_tags=["价格偏高", "新手等待久"],
        specialty_tags=["探险体验"],
        area="晨阳区",
        nearby_areas=["云景", "芳华街"],
    ),
    Venue(
        id="venue_007",
        name="城市桌游馆",
        type="board_game",
        tags=["indoor", "social", "friends", "colleagues", "board_game", "relaxed"],
        distance_km=2.8,
        suggested_duration_minutes=120,
        suggested_duration_min=120,
        suggested_duration_max=180,
        duration_flexibility="medium",
        suitable_age_min=10,
        suitable_age_max=99,
        open_time="10:00",
        close_time="23:00",
        price_per_person=45.0,
        rating=4.4,
        indoor=True,
        requires_ticket=False,
        available_tickets=999,
        walk_intensity="low",
        noise_level="moderate",
        queue_minutes=10,
        review_count=890,
        positive_review_tags=["桌游种类多", "店员热情", "适合团建"],
        negative_review_tags=["周末人多"],
        specialty_tags=["团建首选"],
        area="学府路",
        nearby_areas=["明湖区", "学海村"],
        packages=[
            Package(
                id="pkg_venue007_1",
                title="5人欢乐包 (3小时)",
                price=180.0,
                original_price=225.0,
                includes=["入场费×5", "指定桌游无限畅玩"],
            )
        ],
    ),
    Venue(
        id="venue_008",
        name="老街传统茶馆",
        type="tea_house",
        tags=["indoor", "quiet", "elderly_friendly", "couple", "slow_pace", "tea_house"],
        distance_km=1.5,
        suggested_duration_minutes=90,
        suggested_duration_min=30,
        suggested_duration_max=90,
        duration_flexibility="high",
        suitable_age_min=0,
        suitable_age_max=99,
        open_time="09:00",
        close_time="21:00",
        price_per_person=60.0,
        rating=4.6,
        indoor=True,
        requires_ticket=False,
        available_tickets=999,
        walk_intensity="low",
        noise_level="quiet",
        queue_minutes=5,
        review_count=1120,
        positive_review_tags=["茶香浓郁", "环境古朴", "适合聊天"],
        negative_review_tags=["停车不便"],
        specialty_tags=["情侣首选", "长辈推荐"],
        area="古城区",
        nearby_areas=["南市", "旧市巷"],
        venue_coupons=[
            VenueCoupon(
                id="vc_008",
                title="双人茶位8折",
                discount_type="percent",
                value=0.8,
                min_spend=0.0,
                available=True,
            )
        ],
    ),
    Venue(
        id="venue_009",
        name="步行街文创集市",
        type="citywalk",
        tags=["outdoor", "walk", "photo", "friends", "couple", "social", "citywalk"],
        distance_km=3.0,
        suggested_duration_minutes=100,
        suggested_duration_min=60,
        suggested_duration_max=150,
        duration_flexibility="high",
        suitable_age_min=0,
        suitable_age_max=99,
        open_time="10:00",
        close_time="22:00",
        price_per_person=0.0,
        rating=4.3,
        indoor=False,
        requires_ticket=False,
        available_tickets=999,
        walk_intensity="medium",
        noise_level="moderate",
        queue_minutes=0,
        review_count=2380,
        positive_review_tags=["文创小店多", "氛围好", "拍照出片"],
        negative_review_tags=["节假日人多"],
        specialty_tags=["网红打卡"],
        area="芳华街",
        nearby_areas=["晨阳区", "运动园"],
    ),
    Venue(
        id="venue_010",
        name="密室逃脱体验馆",
        type="escape_room",
        tags=["indoor", "adventure", "friends", "colleagues", "active", "escape_room"],
        distance_km=4.2,
        suggested_duration_minutes=75,
        suggested_duration_min=90,
        suggested_duration_max=120,
        duration_flexibility="low",
        suitable_age_min=12,
        suitable_age_max=60,
        open_time="11:00",
        close_time="23:00",
        price_per_person=98.0,
        rating=4.5,
        indoor=True,
        requires_ticket=True,
        available_tickets=12,
        walk_intensity="medium",
        noise_level="moderate",
        queue_minutes=15,
        review_count=680,
        positive_review_tags=["剧情沉浸", "道具精良", "很刺激"],
        negative_review_tags=["需要提前预约"],
        specialty_tags=["探险体验"],
        area="晨阳区",
        nearby_areas=["芳华街", "云景"],
        packages=[
            Package(
                id="pkg_venue010_1",
                title="4人组队票",
                price=340.0,
                original_price=392.0,
                includes=["密室门票×4"],
            )
        ],
    ),
    Venue(
        id="venue_011",
        name="4DX星耀影城",
        type="movie",
        tags=["indoor", "family_friendly", "couple", "movie", "low_walk"],
        distance_km=3.5,
        suggested_duration_minutes=120,
        suggested_duration_min=120,
        suggested_duration_max=150,
        duration_flexibility="low",
        suitable_age_min=6,
        suitable_age_max=99,
        open_time="10:00",
        close_time="23:30",
        price_per_person=80.0,
        rating=4.4,
        indoor=True,
        requires_ticket=True,
        available_tickets=60,
        walk_intensity="low",
        noise_level="moderate",
        queue_minutes=20,
        review_count=1850,
        positive_review_tags=["4DX体验棒", "画质清晰", "座椅舒适"],
        negative_review_tags=["停车高峰等位"],
        specialty_tags=["情侣首选"],
        area="云景",
        nearby_areas=["晨阳区", "星桥"],
        venue_coupons=[
            VenueCoupon(
                id="vc_011",
                title="双人票立减30元",
                discount_type="fixed",
                value=30.0,
                min_spend=160.0,
                available=True,
            )
        ],
    ),
    Venue(
        id="venue_012",
        name="少儿科学实验馆",
        type="kids_lab",
        tags=["indoor", "kids", "parent_child", "educational", "young_child", "family_friendly"],
        distance_km=4.0,
        suggested_duration_minutes=110,
        suggested_duration_min=90,
        suggested_duration_max=150,
        duration_flexibility="medium",
        suitable_age_min=3,
        suitable_age_max=10,
        open_time="09:00",
        close_time="18:00",
        price_per_person=70.0,
        rating=4.8,
        indoor=True,
        requires_ticket=True,
        available_tickets=25,
        walk_intensity="low",
        noise_level="moderate",
        queue_minutes=10,
        review_count=1640,
        positive_review_tags=["孩子超爱做实验", "老师讲解清楚", "寓教于乐"],
        negative_review_tags=["名额有限需提前订"],
        specialty_tags=["亲子推荐", "科普教育"],
        area="明湖区",
        nearby_areas=["学海村", "学府路"],
        packages=[
            Package(
                id="pkg_venue012_1",
                title="亲子双人套票",
                price=110.0,
                original_price=140.0,
                includes=["成人票×1", "儿童票×1"],
            )
        ],
    ),
    # MVP-4: large theme park for testing "5h not enough for second activity"
    Venue(
        id="venue_013",
        name="超级主题乐园",
        type="theme_park",
        tags=["outdoor", "family_friendly", "kids", "parent_child", "thrill", "large"],
        distance_km=18.0,
        suggested_duration_minutes=300,
        suggested_duration_min=240,
        suggested_duration_max=360,
        duration_flexibility="low",
        suitable_age_min=3,
        suitable_age_max=60,
        open_time="09:00",
        close_time="21:00",
        price_per_person=299.0,
        rating=4.8,
        indoor=False,
        requires_ticket=True,
        available_tickets=200,
        walk_intensity="high",
        noise_level="loud",
        queue_minutes=30,
        review_count=8200,
        positive_review_tags=["项目超多", "孩子玩一天不够", "烟火表演超赞"],
        negative_review_tags=["节假日人山人海", "停车费贵", "园内餐饮贵"],
        specialty_tags=["亲子推荐", "全家出游首选"],
        area="远郊区",
        nearby_areas=["晨阳区"],
    ),
    # MVP-4 expansion: additional venues for richer demo coverage
    Venue(
        id="venue_014",
        name="城郊动物园",
        type="zoo",
        tags=["family_friendly", "parent_child", "kids", "outdoor", "educational", "animals"],
        distance_km=12.0,
        suggested_duration_minutes=150,
        suggested_duration_min=120,
        suggested_duration_max=180,
        duration_flexibility="medium",
        suitable_age_min=2,
        suitable_age_max=80,
        open_time="09:00",
        close_time="17:30",
        price_per_person=80.0,
        rating=4.4,
        indoor=False,
        requires_ticket=True,
        available_tickets=500,
        walk_intensity="medium",
        noise_level="moderate",
        queue_minutes=15,
        review_count=1820,
        positive_review_tags=["动物种类多", "适合亲子", "孩子喜欢"],
        negative_review_tags=["路程较远", "周末人多"],
        specialty_tags=["亲子必去", "教育体验"],
        area="远郊区",
        nearby_areas=["晨阳区"],
        venue_coupons=[
            VenueCoupon(
                id="vc_014",
                title="网购票9折",
                discount_type="percent",
                value=0.9,
                min_spend=0.0,
                available=True,
            )
        ],
        ticket_options=[
            TicketOption(type="adult", price=80.0, note="需出示有效证件"),
            TicketOption(
                type="child",
                price=40.0,
                note="身高1.2米以下免票，需携带户口本或身份证",
            ),
            TicketOption(
                type="senior",
                price=40.0,
                note="60周岁以上，需出示老年证或身份证",
            ),
            TicketOption(type="student", price=50.0, note="需出示学生证"),
        ],
    ),
    Venue(
        id="venue_015",
        name="夜市美食集市",
        type="night_market",
        tags=[
            "friends",
            "social",
            "food",
            "outdoor",
            "night_available",
            "citywalk",
            "photo",
        ],
        distance_km=4.5,
        suggested_duration_minutes=90,
        suggested_duration_min=60,
        suggested_duration_max=120,
        duration_flexibility="high",
        suitable_age_min=6,
        suitable_age_max=80,
        open_time="17:00",
        close_time="23:00",
        price_per_person=0.0,
        rating=4.3,
        indoor=False,
        requires_ticket=False,
        available_tickets=999,
        walk_intensity="low",
        noise_level="loud",
        queue_minutes=5,
        review_count=2340,
        positive_review_tags=["烟火气足", "美食种类多", "拍照出片"],
        negative_review_tags=["晚上才开", "室外较热"],
        specialty_tags=["夜生活", "小吃天堂"],
        area="晨阳区",
        nearby_areas=["芳华街", "东河区"],
    ),
    Venue(
        id="venue_016",
        name="星河购物中心",
        type="mall",
        tags=[
            "family_friendly",
            "friends",
            "shopping",
            "indoor",
            "kids",
            "parent_child",
            "night_available",
        ],
        distance_km=3.2,
        suggested_duration_minutes=120,
        suggested_duration_min=60,
        suggested_duration_max=180,
        duration_flexibility="high",
        suitable_age_min=0,
        suitable_age_max=99,
        open_time="10:00",
        close_time="22:00",
        price_per_person=0.0,
        rating=4.2,
        indoor=True,
        requires_ticket=False,
        available_tickets=999,
        walk_intensity="low",
        noise_level="moderate",
        queue_minutes=0,
        review_count=3120,
        positive_review_tags=["品牌齐全", "室内舒适", "餐饮选择多"],
        negative_review_tags=["节假日停车难", "人流量大"],
        specialty_tags=["一站购物", "家庭首选"],
        area="芳华街",
        nearby_areas=["云景", "东河区"],
    ),
    Venue(
        id="venue_017",
        name="城市音乐现场",
        type="live_show",
        tags=[
            "couple",
            "friends",
            "music",
            "nightlife",
            "date",
            "indoor",
            "night_available",
        ],
        distance_km=5.8,
        suggested_duration_minutes=105,
        suggested_duration_min=90,
        suggested_duration_max=120,
        duration_flexibility="low",
        suitable_age_min=18,
        suitable_age_max=60,
        open_time="19:30",
        close_time="22:30",
        price_per_person=180.0,
        rating=4.6,
        indoor=True,
        requires_ticket=True,
        available_tickets=200,
        walk_intensity="low",
        noise_level="loud",
        queue_minutes=10,
        review_count=890,
        positive_review_tags=["演出精彩", "氛围好", "音效一流"],
        negative_review_tags=["场次较少", "票难抢"],
        specialty_tags=["约会必选", "文艺青年"],
        area="晨阳区",
        nearby_areas=["东河区", "芳华街"],
        venue_coupons=[
            VenueCoupon(
                id="vc_017",
                title="立减20元",
                discount_type="fixed",
                value=20.0,
                min_spend=0.0,
                available=True,
            )
        ],
        ticket_options=[
            TicketOption(type="adult", price=180.0, note="演出票，需提前购买"),
            TicketOption(type="student", price=130.0, note="学生优惠票，需出示学生证"),
        ],
    ),
    Venue(
        id="venue_018",
        name="商场亲子乐园",
        type="indoor_kids_playground",
        tags=[
            "family_friendly",
            "parent_child",
            "kids",
            "indoor",
            "night_available",
            "mall",
        ],
        distance_km=3.5,
        suggested_duration_minutes=120,
        suggested_duration_min=90,
        suggested_duration_max=150,
        duration_flexibility="medium",
        suitable_age_min=1,
        suitable_age_max=12,
        open_time="10:00",
        close_time="22:00",
        price_per_person=120.0,
        rating=4.3,
        indoor=True,
        requires_ticket=True,
        available_tickets=150,
        walk_intensity="low",
        noise_level="loud",
        queue_minutes=10,
        review_count=1430,
        positive_review_tags=["室内凉快", "设施安全", "孩子玩得开心"],
        negative_review_tags=["比较吵闹", "周末需排队预约"],
        specialty_tags=["夜间亲子", "雨天必备"],
        area="芳华街",
        nearby_areas=["云景", "东河区"],
        packages=[
            Package(
                id="pkg_venue018_1",
                title="家庭套餐（2大1小）",
                price=280.0,
                original_price=360.0,
                includes=["成人票×2", "儿童票×1"],
            )
        ],
        venue_coupons=[
            VenueCoupon(
                id="vc_018",
                title="满200减20",
                discount_type="fixed",
                value=20.0,
                min_spend=200.0,
                available=True,
            )
        ],
        ticket_options=[
            TicketOption(type="adult", price=120.0, note="陪同成人票"),
            TicketOption(type="child", price=120.0, note="儿童票（12岁以下）"),
            TicketOption(
                type="family",
                price=280.0,
                note="家庭套票2大1小，需提前预约",
            ),
        ],
    ),
]

_VENUE_MAP: dict[str, Venue] = {v.id: v for v in VENUES}


def get_venue(venue_id: str) -> Venue | None:
    return _VENUE_MAP.get(venue_id)


def search_venues(
    scenario_type: str,
    max_distance_km: float,
    tags: list[str],
) -> list[Venue]:
    results = []
    for venue in VENUES:
        if venue.distance_km > max_distance_km:
            continue
        if tags and not any(t in venue.tags for t in tags):
            continue
        results.append(venue)
    return sorted(results, key=lambda v: (-v.rating, v.distance_km))
